title: Nobita个人博客
description: “Nobita的个人博客”
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ashnobit.github.io"
blog_name: Nobita个人博客
github_sername:  AshNobita
githuburl: "https://github.com/AshNobita"
avatarurl: "avatar.jpg"
baidu_tongji_id: "5516d1ba3fc6eecb6cf4a924c309ec8f"
markdown: kramdown

plugins: [jekyll-paginate]
paginate: 6

